server:
  servlet:
    context-path: /product
  port: 9992
spring:
  jpa:
    show-sql: true
  application:
    name: product catelog
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379